name: "🔗 Feature Request"
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request for this idea already exists.
      options:
        - label: I have searched the existing feature requests
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the feature you'd like to request.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Use Case
      description: Describe how this feature would be beneficial or how it would be used.
    validations:
      required: false
