name: Deployment Pipeline
on:
  push:
    branches:
      [main, 71-add-github-actions-for-building-and-linting-the-frontend]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
